// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterBackupProcedureTemplateListerExpansion allows custom methods to be added to
// ClusterBackupProcedureTemplateLister.
type ClusterBackupProcedureTemplateListerExpansion interface{}

// ClusterBackupProcedureTemplateNamespaceListerExpansion allows custom methods to be added to
// ClusterBackupProcedureTemplateNamespaceLister.
type ClusterBackupProcedureTemplateNamespaceListerExpansion interface{}

// RestoredBackupListerExpansion allows custom methods to be added to
// RestoredBackupLister.
type RestoredBackupListerExpansion interface{}

// RestoredBackupNamespaceListerExpansion allows custom methods to be added to
// RestoredBackupNamespaceLister.
type RestoredBackupNamespaceListerExpansion interface{}

// ScheduledBackupListerExpansion allows custom methods to be added to
// ScheduledBackupLister.
type ScheduledBackupListerExpansion interface{}

// ScheduledBackupNamespaceListerExpansion allows custom methods to be added to
// ScheduledBackupNamespaceLister.
type ScheduledBackupNamespaceListerExpansion interface{}
