// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterBackupProcedureTemplateListerExpansion allows custom methods to be added to
// ClusterBackupProcedureTemplateLister.
type ClusterBackupProcedureTemplateListerExpansion interface{}

// ClusterBackupProcedureTemplateNamespaceListerExpansion allows custom methods to be added to
// ClusterBackupProcedureTemplateNamespaceLister.
type ClusterBackupProcedureTemplateNamespaceListerExpansion interface{}

// RequestedBackupActionListerExpansion allows custom methods to be added to
// RequestedBackupActionLister.
type RequestedBackupActionListerExpansion interface{}

// RequestedBackupActionNamespaceListerExpansion allows custom methods to be added to
// RequestedBackupActionNamespaceLister.
type RequestedBackupActionNamespaceListerExpansion interface{}

// ScheduledBackupListerExpansion allows custom methods to be added to
// ScheduledBackupLister.
type ScheduledBackupListerExpansion interface{}

// ScheduledBackupNamespaceListerExpansion allows custom methods to be added to
// ScheduledBackupNamespaceLister.
type ScheduledBackupNamespaceListerExpansion interface{}
