// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/riotkit-org/backup-maker-operator/pkg/apis/riotkit/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RestoredBackupLister helps list RestoredBackups.
// All objects returned here must be treated as read-only.
type RestoredBackupLister interface {
	// List lists all RestoredBackups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RequestedBackupAction, err error)
	// RestoredBackups returns an object that can list and get RestoredBackups.
	RestoredBackups(namespace string) RestoredBackupNamespaceLister
	RestoredBackupListerExpansion
}

// restoredBackupLister implements the RestoredBackupLister interface.
type restoredBackupLister struct {
	indexer cache.Indexer
}

// NewRestoredBackupLister returns a new RestoredBackupLister.
func NewRestoredBackupLister(indexer cache.Indexer) RestoredBackupLister {
	return &restoredBackupLister{indexer: indexer}
}

// List lists all RestoredBackups in the indexer.
func (s *restoredBackupLister) List(selector labels.Selector) (ret []*v1alpha1.RequestedBackupAction, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RequestedBackupAction))
	})
	return ret, err
}

// RestoredBackups returns an object that can list and get RestoredBackups.
func (s *restoredBackupLister) RestoredBackups(namespace string) RestoredBackupNamespaceLister {
	return restoredBackupNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RestoredBackupNamespaceLister helps list and get RestoredBackups.
// All objects returned here must be treated as read-only.
type RestoredBackupNamespaceLister interface {
	// List lists all RestoredBackups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RequestedBackupAction, err error)
	// Get retrieves the RequestedBackupAction from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.RequestedBackupAction, error)
	RestoredBackupNamespaceListerExpansion
}

// restoredBackupNamespaceLister implements the RestoredBackupNamespaceLister
// interface.
type restoredBackupNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all RestoredBackups in the indexer for a given namespace.
func (s restoredBackupNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.RequestedBackupAction, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RequestedBackupAction))
	})
	return ret, err
}

// Get retrieves the RequestedBackupAction from the indexer for a given namespace and name.
func (s restoredBackupNamespaceLister) Get(name string) (*v1alpha1.RequestedBackupAction, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("restoredbackup"), name)
	}
	return obj.(*v1alpha1.RequestedBackupAction), nil
}
