---
apiVersion: skaffold/v3
kind: Config
build:
    artifacts:
        - image: bm-registry:5000/backup-maker-controller
    local:
        push: true
        useBuildkit: true
    tagPolicy:
        gitCommit: { }
deploy:
    helm:
        releases:
            - name: backup-maker-controller
              chartPath: charts/backup-maker-controller
              recreatePods: true
              namespace: backup-maker-controller
              createNamespace: true
              setValueTemplates:
                  installCRD: "false"
                  image.repository: 'bm-registry:5000/backup-maker-controller'
                  image.tag: '{{.IMAGE_TAG}}'

profiles:
    # ============================================================
    # Uses built-in Redis instead of in-memory locking mechanisms
    # ============================================================
    - name: redis
      patches:
          - op: add
            path: /deploy/helm/releases/0/setValueTemplates/redis.enable
            value: true
          - op: add
            path: /deploy/helm/releases/0/setValueTemplates/redis.deploy
            value: true
