// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	riotkitv1alpha1 "github.com/riotkit-org/backup-maker-operator/pkg/apis/riotkit/v1alpha1"
	versioned "github.com/riotkit-org/backup-maker-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/riotkit-org/backup-maker-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/riotkit-org/backup-maker-operator/pkg/client/listers/riotkit/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterBackupProcedureTemplateInformer provides access to a shared informer and lister for
// ClusterBackupProcedureTemplates.
type ClusterBackupProcedureTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ClusterBackupProcedureTemplateLister
}

type clusterBackupProcedureTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClusterBackupProcedureTemplateInformer constructs a new informer for ClusterBackupProcedureTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterBackupProcedureTemplateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterBackupProcedureTemplateInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredClusterBackupProcedureTemplateInformer constructs a new informer for ClusterBackupProcedureTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterBackupProcedureTemplateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RiotkitV1alpha1().ClusterBackupProcedureTemplates(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RiotkitV1alpha1().ClusterBackupProcedureTemplates(namespace).Watch(context.TODO(), options)
			},
		},
		&riotkitv1alpha1.ClusterBackupProcedureTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterBackupProcedureTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterBackupProcedureTemplateInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterBackupProcedureTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&riotkitv1alpha1.ClusterBackupProcedureTemplate{}, f.defaultInformer)
}

func (f *clusterBackupProcedureTemplateInformer) Lister() v1alpha1.ClusterBackupProcedureTemplateLister {
	return v1alpha1.NewClusterBackupProcedureTemplateLister(f.Informer().GetIndexer())
}
