// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/riotkit-org/backup-maker-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ClusterBackupProcedureTemplates returns a ClusterBackupProcedureTemplateInformer.
	ClusterBackupProcedureTemplates() ClusterBackupProcedureTemplateInformer
	// RestoredBackups returns a RestoredBackupInformer.
	RestoredBackups() RestoredBackupInformer
	// ScheduledBackups returns a ScheduledBackupInformer.
	ScheduledBackups() ScheduledBackupInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ClusterBackupProcedureTemplates returns a ClusterBackupProcedureTemplateInformer.
func (v *version) ClusterBackupProcedureTemplates() ClusterBackupProcedureTemplateInformer {
	return &clusterBackupProcedureTemplateInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RestoredBackups returns a RestoredBackupInformer.
func (v *version) RestoredBackups() RestoredBackupInformer {
	return &restoredBackupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ScheduledBackups returns a ScheduledBackupInformer.
func (v *version) ScheduledBackups() ScheduledBackupInformer {
	return &scheduledBackupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
