// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	riotkitv1alpha1 "github.com/riotkit-org/backup-maker-operator/pkg/apis/riotkit/v1alpha1"
	versioned "github.com/riotkit-org/backup-maker-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/riotkit-org/backup-maker-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/riotkit-org/backup-maker-operator/pkg/client/listers/riotkit/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RequestedBackupActionInformer provides access to a shared informer and lister for
// RequestedBackupActions.
type RequestedBackupActionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RequestedBackupActionLister
}

type requestedBackupActionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRequestedBackupActionInformer constructs a new informer for RequestedBackupAction type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRequestedBackupActionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRequestedBackupActionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRequestedBackupActionInformer constructs a new informer for RequestedBackupAction type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRequestedBackupActionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RiotkitV1alpha1().RequestedBackupActions(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RiotkitV1alpha1().RequestedBackupActions(namespace).Watch(context.TODO(), options)
			},
		},
		&riotkitv1alpha1.RequestedBackupAction{},
		resyncPeriod,
		indexers,
	)
}

func (f *requestedBackupActionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRequestedBackupActionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *requestedBackupActionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&riotkitv1alpha1.RequestedBackupAction{}, f.defaultInformer)
}

func (f *requestedBackupActionInformer) Lister() v1alpha1.RequestedBackupActionLister {
	return v1alpha1.NewRequestedBackupActionLister(f.Informer().GetIndexer())
}
