// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ClusterBackupProcedureTemplateExpansion interface{}

type RequestedBackupActionExpansion interface{}

type ScheduledBackupExpansion interface{}
