// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ClusterBackupProcedureTemplateExpansion interface{}

type RestoredBackupExpansion interface{}

type ScheduledBackupExpansion interface{}
