// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/riotkit-org/backup-maker-operator/pkg/apis/riotkit/v1alpha1"
	scheme "github.com/riotkit-org/backup-maker-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RequestedBackupActionsGetter has a method to return a RequestedBackupActionInterface.
// A group's client should implement this interface.
type RequestedBackupActionsGetter interface {
	RequestedBackupActions(namespace string) RequestedBackupActionInterface
}

// RequestedBackupActionInterface has methods to work with RequestedBackupAction resources.
type RequestedBackupActionInterface interface {
	Create(ctx context.Context, requestedBackupAction *v1alpha1.RequestedBackupAction, opts v1.CreateOptions) (*v1alpha1.RequestedBackupAction, error)
	Update(ctx context.Context, requestedBackupAction *v1alpha1.RequestedBackupAction, opts v1.UpdateOptions) (*v1alpha1.RequestedBackupAction, error)
	UpdateStatus(ctx context.Context, requestedBackupAction *v1alpha1.RequestedBackupAction, opts v1.UpdateOptions) (*v1alpha1.RequestedBackupAction, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.RequestedBackupAction, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RequestedBackupActionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RequestedBackupAction, err error)
	RequestedBackupActionExpansion
}

// requestedBackupActions implements RequestedBackupActionInterface
type requestedBackupActions struct {
	client rest.Interface
	ns     string
}

// newRequestedBackupActions returns a RequestedBackupActions
func newRequestedBackupActions(c *RiotkitV1alpha1Client, namespace string) *requestedBackupActions {
	return &requestedBackupActions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the requestedBackupAction, and returns the corresponding requestedBackupAction object, and an error if there is any.
func (c *requestedBackupActions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RequestedBackupAction, err error) {
	result = &v1alpha1.RequestedBackupAction{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("requestedbackupactions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RequestedBackupActions that match those selectors.
func (c *requestedBackupActions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RequestedBackupActionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RequestedBackupActionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("requestedbackupactions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested requestedBackupActions.
func (c *requestedBackupActions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("requestedbackupactions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a requestedBackupAction and creates it.  Returns the server's representation of the requestedBackupAction, and an error, if there is any.
func (c *requestedBackupActions) Create(ctx context.Context, requestedBackupAction *v1alpha1.RequestedBackupAction, opts v1.CreateOptions) (result *v1alpha1.RequestedBackupAction, err error) {
	result = &v1alpha1.RequestedBackupAction{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("requestedbackupactions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(requestedBackupAction).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a requestedBackupAction and updates it. Returns the server's representation of the requestedBackupAction, and an error, if there is any.
func (c *requestedBackupActions) Update(ctx context.Context, requestedBackupAction *v1alpha1.RequestedBackupAction, opts v1.UpdateOptions) (result *v1alpha1.RequestedBackupAction, err error) {
	result = &v1alpha1.RequestedBackupAction{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("requestedbackupactions").
		Name(requestedBackupAction.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(requestedBackupAction).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *requestedBackupActions) UpdateStatus(ctx context.Context, requestedBackupAction *v1alpha1.RequestedBackupAction, opts v1.UpdateOptions) (result *v1alpha1.RequestedBackupAction, err error) {
	result = &v1alpha1.RequestedBackupAction{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("requestedbackupactions").
		Name(requestedBackupAction.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(requestedBackupAction).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the requestedBackupAction and deletes it. Returns an error if one occurs.
func (c *requestedBackupActions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("requestedbackupactions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *requestedBackupActions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("requestedbackupactions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched requestedBackupAction.
func (c *requestedBackupActions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RequestedBackupAction, err error) {
	result = &v1alpha1.RequestedBackupAction{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("requestedbackupactions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
