// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/riotkit-org/backup-maker-controller/pkg/apis/riotkit/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRequestedBackupActions implements RequestedBackupActionInterface
type FakeRequestedBackupActions struct {
	Fake *FakeRiotkitV1alpha1
	ns   string
}

var requestedbackupactionsResource = schema.GroupVersionResource{Group: "riotkit.org", Version: "v1alpha1", Resource: "requestedbackupactions"}

var requestedbackupactionsKind = schema.GroupVersionKind{Group: "riotkit.org", Version: "v1alpha1", Kind: "RequestedBackupAction"}

// Get takes name of the requestedBackupAction, and returns the corresponding requestedBackupAction object, and an error if there is any.
func (c *FakeRequestedBackupActions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RequestedBackupAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(requestedbackupactionsResource, c.ns, name), &v1alpha1.RequestedBackupAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RequestedBackupAction), err
}

// List takes label and field selectors, and returns the list of RequestedBackupActions that match those selectors.
func (c *FakeRequestedBackupActions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RequestedBackupActionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(requestedbackupactionsResource, requestedbackupactionsKind, c.ns, opts), &v1alpha1.RequestedBackupActionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RequestedBackupActionList{ListMeta: obj.(*v1alpha1.RequestedBackupActionList).ListMeta}
	for _, item := range obj.(*v1alpha1.RequestedBackupActionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested requestedBackupActions.
func (c *FakeRequestedBackupActions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(requestedbackupactionsResource, c.ns, opts))

}

// Create takes the representation of a requestedBackupAction and creates it.  Returns the server's representation of the requestedBackupAction, and an error, if there is any.
func (c *FakeRequestedBackupActions) Create(ctx context.Context, requestedBackupAction *v1alpha1.RequestedBackupAction, opts v1.CreateOptions) (result *v1alpha1.RequestedBackupAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(requestedbackupactionsResource, c.ns, requestedBackupAction), &v1alpha1.RequestedBackupAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RequestedBackupAction), err
}

// Update takes the representation of a requestedBackupAction and updates it. Returns the server's representation of the requestedBackupAction, and an error, if there is any.
func (c *FakeRequestedBackupActions) Update(ctx context.Context, requestedBackupAction *v1alpha1.RequestedBackupAction, opts v1.UpdateOptions) (result *v1alpha1.RequestedBackupAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(requestedbackupactionsResource, c.ns, requestedBackupAction), &v1alpha1.RequestedBackupAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RequestedBackupAction), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRequestedBackupActions) UpdateStatus(ctx context.Context, requestedBackupAction *v1alpha1.RequestedBackupAction, opts v1.UpdateOptions) (*v1alpha1.RequestedBackupAction, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(requestedbackupactionsResource, "status", c.ns, requestedBackupAction), &v1alpha1.RequestedBackupAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RequestedBackupAction), err
}

// Delete takes name of the requestedBackupAction and deletes it. Returns an error if one occurs.
func (c *FakeRequestedBackupActions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(requestedbackupactionsResource, c.ns, name), &v1alpha1.RequestedBackupAction{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRequestedBackupActions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(requestedbackupactionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RequestedBackupActionList{})
	return err
}

// Patch applies the patch and returns the patched requestedBackupAction.
func (c *FakeRequestedBackupActions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RequestedBackupAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(requestedbackupactionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.RequestedBackupAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RequestedBackupAction), err
}
