// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/riotkit-org/backup-maker-controller/pkg/apis/riotkit/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeScheduledBackups implements ScheduledBackupInterface
type FakeScheduledBackups struct {
	Fake *FakeRiotkitV1alpha1
	ns   string
}

var scheduledbackupsResource = schema.GroupVersionResource{Group: "riotkit.org", Version: "v1alpha1", Resource: "scheduledbackups"}

var scheduledbackupsKind = schema.GroupVersionKind{Group: "riotkit.org", Version: "v1alpha1", Kind: "ScheduledBackup"}

// Get takes name of the scheduledBackup, and returns the corresponding scheduledBackup object, and an error if there is any.
func (c *FakeScheduledBackups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ScheduledBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(scheduledbackupsResource, c.ns, name), &v1alpha1.ScheduledBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScheduledBackup), err
}

// List takes label and field selectors, and returns the list of ScheduledBackups that match those selectors.
func (c *FakeScheduledBackups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ScheduledBackupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(scheduledbackupsResource, scheduledbackupsKind, c.ns, opts), &v1alpha1.ScheduledBackupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ScheduledBackupList{ListMeta: obj.(*v1alpha1.ScheduledBackupList).ListMeta}
	for _, item := range obj.(*v1alpha1.ScheduledBackupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested scheduledBackups.
func (c *FakeScheduledBackups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(scheduledbackupsResource, c.ns, opts))

}

// Create takes the representation of a scheduledBackup and creates it.  Returns the server's representation of the scheduledBackup, and an error, if there is any.
func (c *FakeScheduledBackups) Create(ctx context.Context, scheduledBackup *v1alpha1.ScheduledBackup, opts v1.CreateOptions) (result *v1alpha1.ScheduledBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(scheduledbackupsResource, c.ns, scheduledBackup), &v1alpha1.ScheduledBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScheduledBackup), err
}

// Update takes the representation of a scheduledBackup and updates it. Returns the server's representation of the scheduledBackup, and an error, if there is any.
func (c *FakeScheduledBackups) Update(ctx context.Context, scheduledBackup *v1alpha1.ScheduledBackup, opts v1.UpdateOptions) (result *v1alpha1.ScheduledBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(scheduledbackupsResource, c.ns, scheduledBackup), &v1alpha1.ScheduledBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScheduledBackup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeScheduledBackups) UpdateStatus(ctx context.Context, scheduledBackup *v1alpha1.ScheduledBackup, opts v1.UpdateOptions) (*v1alpha1.ScheduledBackup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(scheduledbackupsResource, "status", c.ns, scheduledBackup), &v1alpha1.ScheduledBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScheduledBackup), err
}

// Delete takes name of the scheduledBackup and deletes it. Returns an error if one occurs.
func (c *FakeScheduledBackups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(scheduledbackupsResource, c.ns, name), &v1alpha1.ScheduledBackup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeScheduledBackups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(scheduledbackupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ScheduledBackupList{})
	return err
}

// Patch applies the patch and returns the patched scheduledBackup.
func (c *FakeScheduledBackups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ScheduledBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(scheduledbackupsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ScheduledBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScheduledBackup), err
}
