// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/riotkit-org/backup-maker-operator/pkg/apis/riotkit/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterBackupProcedureTemplates implements ClusterBackupProcedureTemplateInterface
type FakeClusterBackupProcedureTemplates struct {
	Fake *FakeRiotkitV1alpha1
	ns   string
}

var clusterbackupproceduretemplatesResource = schema.GroupVersionResource{Group: "riotkit.org", Version: "v1alpha1", Resource: "clusterbackupproceduretemplates"}

var clusterbackupproceduretemplatesKind = schema.GroupVersionKind{Group: "riotkit.org", Version: "v1alpha1", Kind: "ClusterBackupProcedureTemplate"}

// Get takes name of the clusterBackupProcedureTemplate, and returns the corresponding clusterBackupProcedureTemplate object, and an error if there is any.
func (c *FakeClusterBackupProcedureTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterBackupProcedureTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusterbackupproceduretemplatesResource, c.ns, name), &v1alpha1.ClusterBackupProcedureTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterBackupProcedureTemplate), err
}

// List takes label and field selectors, and returns the list of ClusterBackupProcedureTemplates that match those selectors.
func (c *FakeClusterBackupProcedureTemplates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterBackupProcedureTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusterbackupproceduretemplatesResource, clusterbackupproceduretemplatesKind, c.ns, opts), &v1alpha1.ClusterBackupProcedureTemplateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterBackupProcedureTemplateList{ListMeta: obj.(*v1alpha1.ClusterBackupProcedureTemplateList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterBackupProcedureTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterBackupProcedureTemplates.
func (c *FakeClusterBackupProcedureTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clusterbackupproceduretemplatesResource, c.ns, opts))

}

// Create takes the representation of a clusterBackupProcedureTemplate and creates it.  Returns the server's representation of the clusterBackupProcedureTemplate, and an error, if there is any.
func (c *FakeClusterBackupProcedureTemplates) Create(ctx context.Context, clusterBackupProcedureTemplate *v1alpha1.ClusterBackupProcedureTemplate, opts v1.CreateOptions) (result *v1alpha1.ClusterBackupProcedureTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clusterbackupproceduretemplatesResource, c.ns, clusterBackupProcedureTemplate), &v1alpha1.ClusterBackupProcedureTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterBackupProcedureTemplate), err
}

// Update takes the representation of a clusterBackupProcedureTemplate and updates it. Returns the server's representation of the clusterBackupProcedureTemplate, and an error, if there is any.
func (c *FakeClusterBackupProcedureTemplates) Update(ctx context.Context, clusterBackupProcedureTemplate *v1alpha1.ClusterBackupProcedureTemplate, opts v1.UpdateOptions) (result *v1alpha1.ClusterBackupProcedureTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clusterbackupproceduretemplatesResource, c.ns, clusterBackupProcedureTemplate), &v1alpha1.ClusterBackupProcedureTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterBackupProcedureTemplate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterBackupProcedureTemplates) UpdateStatus(ctx context.Context, clusterBackupProcedureTemplate *v1alpha1.ClusterBackupProcedureTemplate, opts v1.UpdateOptions) (*v1alpha1.ClusterBackupProcedureTemplate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clusterbackupproceduretemplatesResource, "status", c.ns, clusterBackupProcedureTemplate), &v1alpha1.ClusterBackupProcedureTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterBackupProcedureTemplate), err
}

// Delete takes name of the clusterBackupProcedureTemplate and deletes it. Returns an error if one occurs.
func (c *FakeClusterBackupProcedureTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clusterbackupproceduretemplatesResource, c.ns, name), &v1alpha1.ClusterBackupProcedureTemplate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterBackupProcedureTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clusterbackupproceduretemplatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterBackupProcedureTemplateList{})
	return err
}

// Patch applies the patch and returns the patched clusterBackupProcedureTemplate.
func (c *FakeClusterBackupProcedureTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterBackupProcedureTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clusterbackupproceduretemplatesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClusterBackupProcedureTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterBackupProcedureTemplate), err
}
