apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ClusterBackupProcedureTemplate is the Schema for the clusterbackupproceduretemplates
        API
      displayName: Cluster Backup Procedure Template
      kind: ClusterBackupProcedureTemplate
      name: clusterbackupproceduretemplates.riotkit.org
      version: v1alpha1
    - description: RestoredBackup is the Schema for the restoredbackups API
      displayName: Restored Backup
      kind: RestoredBackup
      name: restoredbackups.riotkit.org
      version: v1alpha1
    - description: ScheduledBackup is the Schema for the scheduledbackups API
      displayName: Scheduled Backup
      kind: ScheduledBackup
      name: scheduledbackups.riotkit.org
      version: v1alpha1
  description: Client for Backup Repository, an E2E (GPG based) backup solution for
    bare metal and cloud
  displayName: backup-maker
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - backup
  - gpg
  - e2e
  links:
  - name: Operator
    url: https://operator.domain
  maturity: alpha
  provider:
    name: Riotkit
  version: 0.0.0
