{{ if $.Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ $.Values.serviceAccount.name }}
    labels:
        {{- include "controller.labels" . | nindent 8 }}
{{ end }}
