# permissions for end users to edit clusterbackupproceduretemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterbackupproceduretemplate-editor-role
rules:
- apiGroups:
  - riotkit.org
  resources:
  - clusterbackupproceduretemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - riotkit.org
  resources:
  - clusterbackupproceduretemplates/status
  verbs:
  - get
