# permissions for end users to edit restoredbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restoredbackup-editor-role
rules:
- apiGroups:
  - riotkit.org
  resources:
  - restoredbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - riotkit.org
  resources:
  - restoredbackups/status
  verbs:
  - get
