# permissions for end users to edit scheduledbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduledbackup-editor-role
rules:
- apiGroups:
  - riotkit.org
  resources:
  - scheduledbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - riotkit.org
  resources:
  - scheduledbackups/status
  verbs:
  - get
